### ISSUE TITLE
Readme incorrectly says P key pauses the sim instead of the spacebar

### ISSUE THREAD

**Issue by AnasALD** [QuantumZain/chaotic-system#2]
the title sums it up, this issue is more of a trying to get an idea on how git hub issues work rather than actually writing about a big, am just writing words here for the sake of words. This is the second sentence. After further inspection I've made an interesting observation whereby pressing the spacebar would pause the simulation. Maybe consider updating the README and make sure the pause button is clearly stated within the program. Also, if paused, why not make us drag the balls aroumd?

**Comment by QuantumZain** [comment]
I updated the Readme file in line with this issue.
